### ISSUE TITLE
Error generating OTF files

### ISSUE THREAD

**Issue by caraya** [google/roboto#56]
I've installed the requirements multiple times but I get the same error below. I'm not sure if this is related to #55 or if this is a different issue altogether. 

If #55 is not the cause of this error; where do I need to look at to get this fixed?

PYTHONPATH=:/Users/carlos/code/roboto-src/roboto/scripts/lib python scripts/build-v2.py
BuildNumber: 01290
---------------------
Roboto Thin
----------------------
>> Generating OTF file
Traceback (most recent call last):
  File "scripts/build-v2.py", line 97, in <module>
    proj.generateFont(th.font, "%s/Thin/Regular/Th"%FAMILYNAME)
  File "/Users/carlos/code/roboto-src/roboto/scripts/lib/fontbuild/Build.py", line 181, in generateFont
    builtSuccessfully = saveOTF(newFont, otfName, autohint=self.autohintOTF)
  File "/Users/carlos/code/roboto-src/roboto/scripts/lib/fontbuild/Build.py", line 293, in saveOTF
    reports = compiler.compile(font, destFile, autohint=autohint)
  File "/usr/local/lib/python2.7/site-packages/ufo2fdk/__init__.py", line 88, in compile
    partsCompiler.compile()
  File "/usr/local/lib/python2.7/site-packages/ufo2fdk/makeotfParts.py", line 66, in compile
    self.setupFile_outlineSource(self.paths["outlineSource"])
  File "/usr/local/lib/python2.7/site-packages/ufo2fdk/makeotfParts.py", line 81, in setupFile_outlineSource
    c.compile()
  File "/usr/local/lib/python2.7/site-packages/ufo2fdk/outlineOTF.py", line 77, in compile
    self.setupTable_CFF()
  File "/usr/local/lib/python2.7/site-packages/ufo2fdk/outlineOTF.py", line 654, in setupTable_CFF
    glyph = self.allGlyphs[glyphName]
KeyError: 'Lj'
make: *** [v2] Error 1

**Comment by anthrotype** [comment]
Yes, it's the same issue as #55.
If you're on OSX, you can temporarily fix it by building the fonts from a case-sensitive sparse image (you can create one with Disk Utils).

**Comment by caraya** [comment]
Thanks for the confirmation.
